name: Build Jailbreak Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dpkg
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Prepare repo
        run: |
          rm -rf repo
          mkdir -p repo/debs

          find . -maxdepth 2 -type f -name "*.deb" -exec cp {} repo/debs/ \;

          echo "DEB files:"
          ls -lh repo/debs

      - name: Generate Packages
        run: |
          cd repo

          dpkg-scanpackages -m debs /dev/null > Packages

          gzip -9 -c Packages > Packages.gz

          echo "Packages generated:"
          cat Packages

      - name: Generate Release
        run: |
          cd repo

          cat > Release <<'EOF'
          Origin: Qing Repo
          Label: 清晨
          Suite: stable
          Version: 1.0
          Codename: stable
          Architectures: iphoneos-arm64e
          Components: main
          Description: 清晨ios越狱源，仅自用备份，大部分支持Roothide，arm64e版本
          EOF

      - name: Create nojekyll
        run: |
          touch repo/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          publish_branch: gh-pages
          force_orphan: true
