name: Build Repo

on:
  push:
    branches:
      - main
    paths:
      - "debs/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dpkg-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Build Packages
        run: |
          dpkg-scanpackages -m ./debs /dev/null > Packages
          gzip -kf Packages
          bzip2 -kf Packages

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Packages Packages.gz Packages.bz2
          git diff --cached --quiet || git commit -m "Update Packages"
          git push
